### ISSUE TITLE
How to update the graph from the controller?

### ISSUE THREAD

**Issue by testn** [dainbrump/ng-epoch#9]
It looks like ng-epoch does not provide a mechanism for the controller to tell ng-epoch to update a graph after the data has been changed (not for live-graph). Is there a good way to do that?

**Comment by dainbrump** [comment]
Minor fix. Had everything to do with the binding for the chartData. I've changed the binding to be one-way so that the $onChanges function is triggered automatically. When the data is changed, the chart should update. Keep in mind, there is currently no transition animation for this like there is for the "live" charts.

**Comment by testn** [comment]
while you are at it, you could consider doing the same for chartRange? It seems to be impacted by the same problem. Thanks!
